AliceApi/Areas/MvcMembership/Models/UserAdministration/DetailsViewModel.cs
using System.Collections.Generic;
using System.Web.Security;
using AliceApi.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace AliceApi.Areas.MvcMembership.Models.UserAdministration
{
	public class DetailsViewModel
	{
		#region StatusEnum enum

		public enum StatusEnum
		{
			Offline,
			Online,
			LockedOut,
			Unapproved,
            Unknown,
            SkiingAlps,
            FlyingAlaska,
            DivingMaldives
		}

		#endregion

		public string DisplayName { get; set; }
		public StatusEnum Status { get; set; }
		public ApplicationUser User { get; set; }
		public bool CanResetPassword { get; set; }
		public bool RequirePasswordQuestionAnswerToResetPassword { get; set; }
		public IList<IdentityUserRole> Roles { get; set; }
        public Dictionary<string, string> Rolls { get; set; }
		public bool IsRolesEnabled { get; set; }
	}
}

AliceApi/Controllers/LoggingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Web;
using System.Web.Mvc;

using AliceApi.Helpers;
using AliceApi.Models.Repository;
using AliceApi.Models;
using AliceApi.Models;

using AliceApi.Models.Google.Visualization;
using AliceApi.Services.Paging;
using AliceApi.Services.RSS;

namespace AliceApi.Controllers
{
    //[Authorize]
    public partial class LoggingController : Controller
    {
        private readonly ILogReportingFacade loggingRepository;

        public LoggingController()
        {
            loggingRepository = new LogReportingFacade();
        }

        public LoggingController(ILogReportingFacade repository)
        {
            loggingRepository = repository;
        }

        /// <summary>
        /// Returns the Index view
        /// </summary>
        /// <param name="Period">Text representation of the date time period. eg: Today, Yesterday, Last Week etc.</param>
        /// <param name="LoggerProviderName">Elmah, Log4Net, NLog, Health Monitoring etc</param>
        /// <param name="LogLevel">Debug, Info, Warning, Error, Fatal</param>
        /// <param name="page">The current page index (0 based)</param>
        /// <param name="PageSize">The number of records per page</param>
        /// <returns></returns>
        public ActionResult Index(string Period, string LoggerProviderName, string LogLevel, int? page, int? PageSize)
        {            
            // Set up our default values
            string defaultPeriod = Session["Period"] == null ? "Today" : Session["Period"].ToString();
            string defaultLogType = Session["LoggerProviderName"] == null ? "All" : Session["LoggerProviderName"].ToString();
            string defaultLogLevel = Session["LogLevel"] == null ? "Error" : Session["LogLevel"].ToString();

            // Set up our view model
            LoggingIndexModel model = new LoggingIndexModel();
            

            model.Period = (Period == null) ? defaultPeriod : Period;
            model.LoggerProviderName = (LoggerProviderName == null) ? defaultLogType : LoggerProviderName;
            model.LogLevel = (LogLevel == null) ? defaultLogLevel : LogLevel;
            model.CurrentPageIndex = page.HasValue ? page.Value - 1 : 0;
            model.PageSize = PageSize.HasValue ? PageSize.Value : 20;

            TimePeriod timePeriod = TimePeriodHelper.GetUtcTimePeriod(model.Period);            

            // Grab the data from the database
            model.LogEvents = loggingRepository.GetByDateRangeAndType(model.CurrentPageIndex, model.PageSize, timePeriod.Start, timePeriod.End, model.LoggerProviderName, model.LogLevel);

            // Put this into the ViewModel so our Pager can get at these values
            ViewData["Period"] = model.Period;
            ViewData["LoggerProviderName"] = model.LoggerProviderName;
            ViewData["LogLevel"] = model.LogLevel;
            ViewData["PageSize"] = model.PageSize;

            // Put the info into the Session so that when we browse away from the page and come back that the last settings are rememberd and used.
            Session["Period"] = model.Period;
            Session["LoggerProviderName"] = model.LoggerProviderName;
            Session["LogLevel"] = model.LogLevel;

            int i = model.LogEvents.TotalItemCount;
            int ii = model.LogEvents.PageNumber;
            int iii = model.LogEvents.PageCount;
            
            return View(model);
        }

        //
        // GET: /Logging/Details/5
        public ActionResult Details(string loggerProviderName, string id)
        {
            LogEvent logEvent = loggingRepository.GetById(loggerProviderName, id);

            return View(logEvent);
        }   

        // string Period, string LoggerProviderName, string LogLevel, int? page, int? PageSize
        public ActionResult Search()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="Period"></param>
        /// <param name="LoggerProviderName"></param>
        /// <param name="LogLevel"></param>
        /// <returns></returns>
        public JsonResult ChartData(string Period, string LoggerProviderName, string LogLevel)
        {                        
            if (Period == "Today" || Period == "Yesterday")
            {
                return ChartDataByHour(Period, LoggerProviderName, LogLevel);
            }
            else
            {
                ChartDataByDay(Period, LoggerProviderName, LogLevel);

                return ChartDataByDay(Period, LoggerProviderName, LogLevel);
            }
        }        

        /// <summary>
        /// 
        /// </summary>
        /// <param name="Period"></param>
        /// <param name="LoggerProviderName"></param>
        /// <param name="logLevel"></param>
        /// <returns></returns>
        public JsonResult ChartDataByHour(string Period, string LoggerProviderName, string logLevel)
        {
            Func<LogEvent, Object> groupByClause = c => c.LogDate.ToLocalTime().Hour;

            return ChartDataByTimePeriod(Period, LoggerProviderName, logLevel, "", groupByClause);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="Period"></param>
        /// <param name="LoggerProviderName"></param>
        /// <param name="logLevel"></param>
        /// <returns></returns>
        public JsonResult ChartDataByDay(string Period, string LoggerProviderName, string logLevel)
        {
            Func<LogEvent, Object> groupByClause = c => c.LogDate.ToLocalTime().Date;
            
            return ChartDataByTimePeriod(Period, LoggerProviderName, logLevel, "dd/MM/yyyy", groupByClause);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="Period"></param>
        /// <param name="LoggerProviderName"></param>
        /// <param name="logLevel"></param>
        /// <param name="keyFormatString"></param>
        /// <param name="groupByClause"></param>
        /// <returns></returns>
        public JsonResult ChartDataByTimePeriod(string Period, string LoggerProviderName, string logLevel, string keyFormatString, Func<LogEvent, Object> groupByClause)
        {
            TimePeriod timePeriod = TimePeriodHelper.GetUtcTimePeriod(Period);

            // Grab ALL entries for the chart (DO NOT PAGE REPORTING DATA!!!)
            IPagedList<LogEvent> chartEntries = loggingRepository.GetByDateRangeAndType(0, Int32.MaxValue, timePeriod.Start, timePeriod.End, LoggerProviderName, logLevel);

            var groupedByDate = chartEntries.GroupBy(groupByClause).OrderBy(y => y.Key);

            var groupedByDateAndThenName = groupedByDate.Select(group => new { Key = group.Key, NestedGroup = group.ToLookup(result => result.LoggerProviderName, result => result.Id) });

            var LoggerNames = (from logEvent in chartEntries
                               select new { Name = logEvent.LoggerProviderName }
                               ).Distinct().OrderBy(item => item.Name);

            ChartData chartData = new ChartData();

            // Add columns
            chartData.AddColumn(new ChartColumn("0", "Period", "string"));
            int columnIndex = 1;
            foreach (var name in LoggerNames)
            {
                chartData.AddColumn(new ChartColumn(columnIndex.ToString(), name.Name.ToString(), "number"));
                columnIndex++;
            }

            // add row data
            foreach (var myDate in groupedByDateAndThenName)
            {
                ChartRow row = new ChartRow();

                string dateString = (myDate.Key is DateTime) ? ((DateTime)myDate.Key).ToString(keyFormatString) : myDate.Key.ToString();
                row.AddCellItem(new ChartCellItem(dateString, ""));

                foreach (var name in LoggerNames)
                {
                    bool valueFound = false;
                    foreach (var myLogger in myDate.NestedGroup)
                    {
                        if (myLogger.Key == name.Name.ToString())
                        {
                            row.AddCellItem(new ChartCellItem(myLogger.Count(), ""));
                            valueFound = true;
                        }
                    }
                    if (!valueFound) row.AddCellItem(new ChartCellItem(0, ""));
                }

                chartData.AddRow(row);
            }

            return Json(chartData, "text/x-json", System.Text.Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Gets the chart
        /// </summary>
        /// <param name="Period"></param>
        /// <param name="LoggerProviderName"></param>
        /// <param name="LogLevel"></param>
        /// <returns></returns>
        public ActionResult Chart(string Period, string LoggerProviderName, string LogLevel)
        {            
            string defaultPeriod = Session["Period"] == null ? "Today" : Session["Period"].ToString();
            string defaultLoggerProviderName = Session["LoggerProviderName"] == null ? "All" : Session["LoggerProviderName"].ToString();
            string defaultLogLevel = Session["LogLevel"] == null ? "Error" : Session["LogLevel"].ToString();

            LoggingIndexModel model = new LoggingIndexModel();

            model.Period = (Period == null) ? defaultPeriod : Period;
            model.LoggerProviderName = (LoggerProviderName == null) ? defaultLoggerProviderName : LoggerProviderName;
            model.LogLevel = (LogLevel == null) ? defaultLogLevel : LogLevel;

            return View(model);
        }







        #region Manage Logs
        /// <summary>
        /// Filter Button - Does the same thing as INDEX but is on the Manage View. 
        /// </summary>
        /// <param name="Period"></param>
        /// <param name="LoggerProviderName"></param>

AliceApi/Views/Logging/Chart.cshtml
@{
//Layout = "~/Views/Shared/DontModify/HomeLayout.cshtml";
}
@*@using Sde.WebApps.Mvc3Template;*@
@*@using Sde.WebApps.Mvc3Template.ViewModels;*@
@using AliceApi;
@using System.Web.Optimization;
@using AliceApi.Models;
@using AliceApi.Helpers;
@using AliceApi.Services.Paging;

@model LoggingIndexModel

<h3>Chart</h3>

<div class="row">
    <div class="col-md-12">



        @using (Html.BeginForm("Chart", "Logging", FormMethod.Get, new { id = "myform" }))
        {

            <div class="grid-options">
                View :
                @Html.ActionLink("List", "Index")
                | <strong>Chart</strong>
                | @Html.ActionLink("RSS", "RssFeed", new { LoggerProviderName = Model.LoggerProviderName, Period = Model.Period, LogLevel = Model.LogLevel }, new { target = "_blank" })
            </div>

            <div class="grid-filter">
                <div class="inner">

                    Logger : @Html.DropDownList("LoggerProviderName", new SelectList(AliceApi.Helpers.FormsHelper.LogProviderNames, "Value", "Text"))
                    Level : @Html.DropDownList("LogLevel", new SelectList(AliceApi.Helpers.FormsHelper.LogLevels, "Value", "Text"))
                    For : @Html.DropDownList("Period", new SelectList(AliceApi.Helpers.FormsHelper.CommonTimePeriods, "Value", "Text"))

                    <input id="btnGo" name="btnGo" type="submit" value="Apply Filter" />

                </div>
            </div>


        }

        <script type="text/javascript" src="http://www.google.com/jsapi"></script>

        <script type="text/javascript">

        // Load the Visualization API and the corechart package.
        google.load("visualization", "1", { packages: ["corechart"] });

        // Set a callback to run when the Google Visualization API is loaded.
        google.setOnLoadCallback(drawChart);

        function drawChart() {

            var loggerProviderName = $("#LoggerProviderName").val();
            var period = $("#Period").val();
            var logLevel = $("#LogLevel").val();

            var actionUrl = "/Logging/ChartData";
            actionUrl += "?LoggerProviderName=" + loggerProviderName;
            actionUrl += "&Period=" + period;
            actionUrl += "&LogLevel=" + logLevel;

            // alert(actionUrl);

            var testJson = $.getJSON(actionUrl, function (chartdata) {

                var data = new google.visualization.DataTable();

                // column
                for (var col = 0; col < chartdata.cols.length; col++) {
                    data.addColumn(chartdata.cols[col].type, chartdata.cols[col].label);
                }

                // row
                for (var row = 0; row < chartdata.rows.length; row++) {

                    data.addRow();

                    for (var col = 0; col < chartdata.cols.length; col++) {

                        var myRow = chartdata.rows[row];
                        var myCell = myRow.c[col];

                        data.setCell(row, col, myCell.v);
                    }
                }

                var options = { 'width': 750, 'height': 450, 'title': 'Logging' };

                var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
                chart.draw(data, options);

            });

        }

        </script>
        <div id="chartContainer">
            <div id="chart_div"></div>
        </div>

    </div>
</div>

AliceApi/Views/Logging/Details.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*@using Sde.WebApps.Mvc3Template;*@
@*@using Sde.WebApps.Mvc3Template.ViewModels;*@
@using AliceApi;
@using System.Web.Optimization;
@using AliceApi.Models;
@using AliceApi.Helpers;
@using AliceApi.Services.Paging;


@model AliceApi.Models.LogEvent

<h3>Details</h3>
<div class="row">
    <div class="col-md-12">
        <p>
            @Html.ActionLink("Back to List", "Index")
        </p>

        <fieldset>
            <legend>Fields</legend>

            <div class="display-label">Id</div>
            <div class="display-field">@Model.Id</div>

            <div class="display-label">LogDate</div>
            <div class="display-field">@String.Format("{0:g}", Model.LogDate)</div>

            <div class="display-label">Name</div>
            <div class="display-field">@Model.LoggerProviderName</div>

            <div class="display-label">Source</div>
            <div class="display-field">@Model.Source</div>

            <div class="display-label">MachineName</div>
            <div class="display-field">@Model.MachineName</div>

            <div class="display-label">Type</div>
            <div class="display-field">@Model.Type</div>

            <div class="display-label">Level</div>
            <div class="display-field">@Model.Level</div>

            <div class="display-label">Message</div>
            <div class="display-field">
                <pre>@Model.Message.WordWrap(80) </pre>
            </div>

            <div class="display-label">StackTrace</div>
            <div class="display-field">@Model.StackTrace </div>

        </fieldset>

        <pre>
            @Html.Raw(FormsHelper.OutputXmlTableForLogging(Model.AllXml).ToString())
        </pre>
        
        <p>
            @Html.ActionLink("Back to List", "Index")
        </p>

    </div>
</div>

AliceApi/Views/Logging/Index.cshtml
@{
    //Layout = "~/Views/Shared/DontModify/HomeLayout.cshtml";
}
@using System.Web.Optimization;
@using AliceApi;
@using AliceApi.Models;
@using AliceApi.Helpers;
@using AliceApi.Services.Paging;

@model LoggingIndexModel

<h3>Logging</h3>
<hr/>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Index", "Logging", new {CurrentPageIndex = 1}, FormMethod.Get, new {id = "myform"}))
        {

            <div class="grid-options">
                View : <strong>List</strong> | @Html.ActionLink("Chart", "Chart")
                | @Html.ActionLink("RSS", "RssFeed", new {LoggerProviderName = Model.LoggerProviderName, Period = Model.Period, LogLevel = Model.LogLevel}, new {target = "_blank"})
                | @Html.ActionLink("Manage", "Manage", "Logging")
                | @Html.ActionLink("Search", "Search")
            </div>

            <div class="grid-filter">
                <div class="inner">
                    Logger : @Html.DropDownList("LoggerProviderName", new SelectList(FormsHelper.LogProviderNames, "Value", "Text"))
                    Level : @Html.DropDownList("LogLevel", new SelectList(FormsHelper.LogLevels, "Value", "Text"))
                    For : @Html.DropDownList("Period", new SelectList(FormsHelper.CommonTimePeriods, "Value", "Text"))
                    <input id="btnGo" name="btnGo" type="submit" value="Apply Filter"/>
                </div>
            </div>

            <div class="grid-header">
                <div class="grid-results">
                    <div class="inner">
                        <span style="float: left">
                            @string.Format("{0} records found. Page {1} of {2}", Model.LogEvents.TotalItemCount, Model.LogEvents.PageNumber, Model.LogEvents.PageCount)
                        </span><span style="float: right">
                            Show @Html.DropDownList("PageSize", new SelectList(FormsHelper.PagingPageSizes, "Value", "Text"), new {onchange = "document.getElementById('myform').submit()"})
                            results per page
                        </span>
                        <div style="clear: both">
                        </div>
                    </div>
                </div>
                <div class="paging">
                    <div class="pager">
                        @Html.Raw(Html.Pager(ViewData.Model.LogEvents.PageSize, ViewData.Model.LogEvents.PageNumber, ViewData.Model.LogEvents.TotalItemCount, new {LoggerProviderName = ViewData["LoggerProviderName"], LogLevel = ViewData["LogLevel"], Period = ViewData["Period"], PageSize = ViewData["PageSize"]}))
                    </div>
                </div>
            </div>

        }


        <div class="grid-container">
            @if (!Model.LogEvents.Any())
            {@:
                <p>No results found</p>
            }
            else
            {
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th></th>
                        <th>#</th>
                        <th>Log</th>
                        <th>Date</th>
                        <th style='white-space: nowrap;'>Time ago</th>
                        <th>Host</th>
                        <th>Source</th>
                        <th>Message</th>
                        <th>Type</th>
                        <th>Level</th>
                    </tr>
                    </thead>
                    <tbody>
                    @{int i = 0;}
                    @foreach (var item in Model.LogEvents)
                    {

                        <tr class="@(i++%2 == 1 ? "alt" : "")">
                            <td>
                                @Html.ActionLink("Details", "Details", new {id = item.Id.ToString(), loggerProviderName = item.LoggerProviderName})
                            </td>
                            <td>
                                @i.ToString()
                            </td>
                            <td>
                                @item.LoggerProviderName
                            </td>
                            <td style='white-space: nowrap;'>
                                @String.Format("{0:g}", item.LogDate.ToLocalTime())
                            </td>
                            <td style='white-space: nowrap;'>
                                @item.LogDate.ToLocalTime().TimeAgoString()
                            </td>
                            <td>
                                @item.MachineName
                            </td>
                            <td>
                                @item.Source
                            </td>
                            <td>
                                <pre>@item.Message.WordWrap(40) </pre>
                            </td>
                            <td>
                                @item.Type
                            </td>
                            <td>
                                @item.Level.ToLower().ToPascalCase()
                            </td>
                        </tr>

                    }
                    </tbody>
                </table>

            }
        </div>



        <div class="grid-header">
            <div class="paging">
                <div class="pager">
                    @Html.Raw(Html.Pager(ViewData.Model.LogEvents.PageSize, ViewData.Model.LogEvents.PageNumber, ViewData.Model.LogEvents.TotalItemCount, new {LogType = ViewData["LogType"], Period = ViewData["Period"], PageSize = ViewData["PageSize"]}))
                </div>
            </div>
        </div>
    </div>

</div>

AliceApi/Views/Logging/Manage.cshtml
@{
    //Layout = "~/Views/Shared/DontModify/HomeLayout.cshtml";
}
@*@using Sde.WebApps.Mvc3Template;*@ 
@*@using Sde.WebApps.Mvc3Template.ViewModels;*@
@using AliceApi;
@using System.Web.Optimization;
@using AliceApi.Models;
@using AliceApi.Helpers;
@using AliceApi.Services.Paging;


@model LoggingManageModel
<script type="text/javascript">
    $(function () {
        $('.datePicker').datepicker({
            dateFormat: "mm-dd-yy"
        });
    });
</script>           
       <h4>Manage</h4>

<div id="errorMessage">@Session["Message"]</div>

@using (Html.BeginForm("Manage", "Logging", new { CurrentPageIndex = 1 }, FormMethod.Post, new { id = "myform" }))
{

    <div class="grid-options">
        View : @Html.ActionLink("List", "Index", "Logging") | @Html.ActionLink("Chart", "Chart")
        | @Html.ActionLink("RSS", "RssFeed", new { LoggerProviderName = Model.LoggerProviderName, Period = Model.Period, LogLevel = Model.LogLevel }, new { target = "_blank" })
        | <strong>Manage</strong>
        | @Html.ActionLink("Search", "Search", "Logging")
    </div> 
			
    <div class="grid-filter">
        <div class="inner">
            Logger : @Html.DropDownList("LoggerProviderName", new SelectList(FormsHelper.LogProviderNames, "Value", "Text"))
            Level : @Html.DropDownList("LogLevel", new SelectList(FormsHelper.LogLevels, "Value", "Text"))
            For : @Html.DropDownList("Period", new SelectList(AliceApi.Helpers.FormsHelper.CommonTimePeriods, "Value", "Text"))
            
@*            <input style="width: 85px;height: 13px; padding-top: 2px;" class="datePicker" type="text" id="txtDateStart" name="txtDateStart" /> 
            and <input style="width: 85px; height: 13px;padding-top: 2px;" class="datePicker" type="text" id="txtDateEnd" name="txtDateEnd" /> &nbsp;*@
            <input id="btnFilter" name="btnFilter" type="submit" value="Apply Filter" class="button-sm ltgrey" />
        </div>
    </div>
			
    <div class="grid-header">
        <div class="grid-results">
            <div class="inner">
                <span style="float: left">
                    @string.Format("{0} records found. Page {1} of {2}", Model.LogEvents.TotalItemCount, Model.LogEvents.PageNumber, Model.LogEvents.PageCount)
                </span><span style="float: right">Show @Html.DropDownList("PageSize", new SelectList(FormsHelper.PagingPageSizes, "Value", "Text"), new { onchange = "document.getElementById('myform').submit()" })
                    results per page </span>
                <div style="clear: both"></div>
            </div>
        </div>
        <div class="paging">
            <div class="pager">                
                @Html.Raw(Html.Pager(ViewData.Model.LogEvents.PageSize, ViewData.Model.LogEvents.PageNumber, ViewData.Model.LogEvents.TotalItemCount, new { LoggerProviderName = ViewData["LoggerProviderName"], LogLevel = ViewData["LogLevel"], Period = ViewData["Period"], PageSize = ViewData["PageSize"] }))
            </div>
            <input id="btnDelete" name="btnDelete" type="submit" value="Delete This Set" class="button-sm ltgrey" style="float: right; margin-top: -25px; margin-right: 170px;" /><input id="btnClear" name="btnClearAllLogs" type="submit" value="SCORTCH THE EARTH" class="button-sm scortch" style="float: right; margin-top: -25px;" OnClick="return confirm('ARE YOU SURE YOU WANT TO DO THIS?\nDELETES EVERYTHING (logs) FROM EVERYWHERE!');" />
        </div>
    </div>   
			
}
@if (Model.LogEvents.Count() == 0)
{ 
    @:<p>No results found</p>
}
else
{  	   
    <div class="grid-container" style="width: 100%; border: 1px solid #000;">
        <table class="grid" >
            <tr>
                <th>Details</th>
                @*<th>#</th>*@
                <th>
                    Log Info
                </th>
                <th>
                   Error Message 
                </th>
              @*  <th style='white-space: nowrap;'>More...</th>*@
                @*<th>Message</th>
                <th>Host</th>
                <th>Source</th>
                <th>Type</th>
                <th>Level</th>*@
            </tr>
            @{int i = 0;}
            @foreach (var item in Model.LogEvents)
            { 	   
                <tr class="@(i++ % 2 == 1 ? "alt" : "")">
                    <td>
                        <div style="">
                            @Html.ActionLink("Details", "Details", new { id = item.Id.ToString(), loggerProviderName = item.LoggerProviderName }, new { @class = "details-icon", @title = "Details", @alt = "Details" })
                            @Html.ActionLink("Details", "Details", new { id = item.Id.ToString(), loggerProviderName = item.LoggerProviderName })
                        </div>
                    </td>
                    <td>
                        <div style="width: 280px">
                            <strong>Log:</strong> @item.LoggerProviderName <br />
                            <strong>Log Level:</strong> @item.Level.ToLower().ToPascalCase() <br />
                            <strong>Date:</strong> @String.Format("{0:g}", item.LogDate.ToLocalTime()) (@item.LogDate.ToLocalTime().TimeAgoString())<br />
                            <strong>Host:</strong>  @item.MachineName <br />
                            <strong>Source:</strong> @item.Source.Chop(30) <br />
                            <strong>Type:</strong> @item.Type <br />
                       </div>
                    </td>
                    <td>
                        <div style="width: 402px">
                            <pre>@item.Message.WordWrap(50)</pre>
                        </div>
                    </td>
                  @*<td style='white-space: nowrap;'></td>*@
                  @*<td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>*@
                </tr>
	   
            }
        </table>
    </div>
	
		
}
<div class="grid-header">
    <div class="paging">
        <div class="pager">
            @Html.Raw(Html.Pager(ViewData.Model.LogEvents.PageSize, ViewData.Model.LogEvents.PageNumber, ViewData.Model.LogEvents.TotalItemCount, new { LogType = ViewData["LogType"], Period = ViewData["Period"], PageSize = ViewData["PageSize"] }))
        </div>
    </div>
</div>

AliceApi/Views/Logging/Search.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*@using Sde.WebApps.Mvc3Template;*@ 
@*@using Sde.WebApps.Mvc3Template.ViewModels;*@
@using AliceApi;
@*@using System.Web.Optimization;
@using Sde.Web.Mvc;*@
@using AliceApi.Models;
@using AliceApi.Helpers;
@using AliceApi.Services.Paging;




@* skipping section headContent*@ @*@section sidebarContent{
	@Html.Menu(SideMenu.Name, "h2", "Links")
}*@




@model LoggingIndexModel
        
<h4>Search</h4>
<script type="text/javascript">
    $(function () {
        $('.datePicker').datepicker({
            dateFormat: "mm-dd-yy"
        });
    });
</script>


    <div class="grid-options">
        View : @Html.ActionLink("List", "Index", "Logging") | @Html.ActionLink("Chart", "Chart")
        | <span style="color: #c0c0c0;">RSS</span>
        @*| @Html.ActionLink("RSS", "RssFeed", new { LoggerProviderName = Model.LoggerProviderName, Period = Model.Period, LogLevel = Model.LogLevel }, new { target = "_blank" })*@
        | @Html.ActionLink("Manage", "Manage", "Logging")
        | <strong>Search</strong>
    </div> 


    <div class="grid-filter">        
        <div class="inner">

        <table>
            <tr>
                <td>Logger</td>
                <td>@Html.DropDownList("LoggerProviderName", new SelectList(AliceApi.Helpers.FormsHelper.LogProviderNames, "Value", "Text")) </td>
            </tr>
            <tr>
                <td>Level</td>
                <td>@Html.DropDownList("LogLevel", new SelectList(AliceApi.Helpers.FormsHelper.LogLevels, "Value", "Text"))  </td>
            </tr>
            <tr>
                <td>For</td>
                <td>
                    <input type="radio" id="dateOption1" name="dateoption" /> @Html.DropDownList("Period", new SelectList(AliceApi.Helpers.FormsHelper.CommonTimePeriods, "Value", "Text"))                    
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="radio" id="dateOption2" name="dateoption" /> 
                    <input style="width: 85px;" class="datePicker" type="text" id="txtDateStart" name="txtDateStart" /> and <input style="width: 85px;" class="datePicker" type="text" id="txtDateEnd" name="txtDateEnd" />
                </td>
            </tr>
            <tr>
                <td>Search criteria</td>
                <td>
                    <textarea id="criteria" name="criteria" rows="3" cols="60"></textarea>
                </td>
            </tr>
            <tr>
                <td></td>
                <td style="text-align: right;">
                    <input id="btnGo" name="btnGo" type="submit" value="Search" class="button ltgrey" />                      
                </td>
            </tr>
        </table>

        </div>
    </div>