AliceApi/Areas/MvcMembership/Models/UserAdministration/CreateUserViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using DataAnnotationsExtensions;

namespace AliceApi.Areas.MvcMembership.Models.UserAdministration
{
	public class CreateUserViewModel
	{
		[Display(Name = "User Name")]
		[Required]
		public string Username { get; set; }

		[Required, DataType(DataType.Password)]
		public string Password { get; set; }

		[Display(Name = "Password (Again...)")]
		[Required, DataType(DataType.Password)]
		public string ConfirmPassword { get; set; }

		[Display(Name = "Email Address")]
		[Required, Email]
		public string Email { get; set; }

		[Display(Name = "Secret Question")]
		public string PasswordQuestion { get; set; }

		[StringLength(100)]
		[Display(Name = "Secret Answer")]
		public string PasswordAnswer { get; set; }

		[Display(Name = "Initial Roles")]
		public IDictionary<string, bool> InitialRoles { get; set; }
	}
}

AliceApi/Areas/MvcMembership/Models/UserAdministration/DetailsViewModel.cs
using System.Collections.Generic;
using System.Web.Security;
using AliceApi.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace AliceApi.Areas.MvcMembership.Models.UserAdministration
{
	public class DetailsViewModel
	{
		#region StatusEnum enum

		public enum StatusEnum
		{
			Offline,
			Online,
			LockedOut,
			Unapproved,
            Unknown,
            SkiingAlps,
            FlyingAlaska,
            DivingMaldives
		}

		#endregion

		public string DisplayName { get; set; }
		public StatusEnum Status { get; set; }
		public ApplicationUser User { get; set; }
		public bool CanResetPassword { get; set; }
		public bool RequirePasswordQuestionAnswerToResetPassword { get; set; }
		public IList<IdentityUserRole> Roles { get; set; }
        public Dictionary<string, string> Rolls { get; set; }
		public bool IsRolesEnabled { get; set; }
	}
}

AliceApi/Areas/MvcMembership/Models/UserAdministration/IndexViewModel.cs
using System.Collections.Generic;
using System.Web.Security;
using AliceApi.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;

namespace AliceApi.Areas.MvcMembership.Models.UserAdministration
{
	public class IndexViewModel
	{
		public string Search { get; set; }
		//public IPagedList<MembershipUser> Users { get; set; }
        public IPagedList<ApplicationUser> Users { get; set; }
        public IEnumerable<IdentityRole> Roles { get; set; }
		public bool IsRolesEnabled { get; set; }
	}
}

AliceApi/Areas/MvcMembership/Models/UserAdministration/RoleViewModel.cs
using System.Collections.Generic;
using System.Web.Security;
using AliceApi.Models;

namespace AliceApi.Areas.MvcMembership.Models.UserAdministration
{
	public class RoleViewModel
	{
		public string Role { get; set; }
		public IList<ApplicationUser> Users { get; set; }
	}
}

AliceApi/Areas/MvcMembership/Controllers/UserAdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;
using System.Web.Security;
using MvcMembership;
using MvcMembership.Settings;
using AliceApi.Areas.MvcMembership.Models.UserAdministration;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace AliceApi.Areas.MvcMembership.Controllers
{
	//[AuthorizeUnlessOnlyUser(Roles = "Administrator")] // allows access if you're the only user, only validates role if role provider is enabled
	public class UserAdministrationController : Controller
	{
		private const int PageSize = 10;
		private const string ResetPasswordBody = "Your new password is: ";
		private const string ResetPasswordSubject = "Your New Password";
		private readonly IRolesService _rolesService;
		private readonly ISmtpClient _smtpClient;
		private readonly IMembershipSettings _membershipSettings;
		private readonly IUserService _userService;
		private readonly IPasswordService _passwordService;

        public UserAdministrationController()
        {
        }

        //public UserAdministrationController()
        //	: this(new AspNetMembershipProviderWrapper(), new AspNetRoleProviderWrapper(), new SmtpClientProxy())
        //{
        //}

        //public UserAdministrationController(AspNetMembershipProviderWrapper membership, IRolesService roles, ISmtpClient smtp)
        //	: this(membership.Settings, membership, membership, roles, smtp)
        //{
        //}

        public UserAdministrationController(
			IMembershipSettings membershipSettings,
			IUserService userService,
			IPasswordService passwordService,
			IRolesService rolesService,
			ISmtpClient smtpClient)
		{
			_membershipSettings = membershipSettings;
			_userService = userService;
			_passwordService = passwordService;
			_rolesService = rolesService;
			_smtpClient = smtpClient;
		}

		public ActionResult Index(int? page, string search = "")
		{

            var userService = new AspNetMembershipProviderWrapper();

            //var roll = new IdentityRole { Name = "Admin" };
            //if (!_userService.RoleManager.RoleExists(roll.Name))
            //    _userService.RoleManager.Create(roll);

            //roll = _userService.RoleManager.FindByName("Admin");
            //var iRole = new IdentityUserRole()
            //{
            //    RoleId = roll.Id,
            //    UserId = userId
            //};

            //if (!await UserManager.IsInRoleAsync(userId, roll.Name))
            //{
            //    user.Roles.Add(iRole);
            //    RoleManager.Update(roll);
            //}

            var users = string.IsNullOrWhiteSpace(search)
				? userService.FindAll(page ?? 1, PageSize)
				: search.Contains("@")
					? userService.FindByEmail(search, page ?? 1, PageSize)
					: userService.FindByUserName(search, page ?? 1, PageSize);

			if (!string.IsNullOrWhiteSpace(search) && users.Count == 1)
				return RedirectToAction("Details", new {id = users[0].Id.ToString()});

            return View(new IndexViewModel
                            {
                                Search = search,
                                Users = users,
                                Roles = userService.RoleManager.Roles,
                                IsRolesEnabled = userService.RoleManager.Roles.Any()
            });

		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult CreateRole(string name)
		{
            var userService = new AspNetMembershipProviderWrapper();
		    var rs = userService.RoleManager;

		    if (!rs.RoleExistsAsync(name.Trim()).Result)
		        rs.Create(new IdentityRole() {Name = name.Trim()});

			return RedirectToAction("Index");
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult DeleteRole(string id)
		{
            var userService = new AspNetMembershipProviderWrapper();

            var role = userService.RoleManager.FindByIdAsync(id).Result;
		    userService.RoleManager.DeleteAsync(role);
            
            //_rolesService.Delete(id);
			return RedirectToAction("Index");
		}

		public ViewResult Role(string id)
		{
            var userService = new AspNetMembershipProviderWrapper();

		    var roleName = userService.RoleManager.FindByIdAsync(id).Result.Name;
            return View(new RoleViewModel
							{
								Role = roleName,
								Users = userService.FindUsersByRoleId(id)
							});
		}

		public ViewResult Details(Guid id)
		{
            var userService = new AspNetMembershipProviderWrapper();
		    var user = userService.SignInManager.UserManager.Users.FirstOrDefault(w => w.Id == id.ToString());
            //var user = _userService.Get(id);

		    //var userRoles = userService.FindUsersByRoleId(id.ToString());// userService.RoleManager.Roles. _rolesService.Enabled ? _rolesService.FindByUser(user) : Enumerable.Empty<string>();

            Dictionary<string, string> rolls  = user.Roles.ToDictionary(role => role.RoleId, role => userService.RoleManager.FindByIdAsync(role.RoleId).Result.Name);

		    var foo = rolls;

            return View(new DetailsViewModel
							{
								//CanResetPassword = _membershipSettings.Password.ResetOrRetrieval.CanReset,
								//RequirePasswordQuestionAnswerToResetPassword = _membershipSettings.Password.ResetOrRetrieval.RequiresQuestionAndAnswer,
								DisplayName = user.UserName,
								User = user,
								Roles = user.Roles.ToList(),
                                Rolls = rolls,
								IsRolesEnabled = true,// _rolesService.Enabled,
								Status = DetailsViewModel.StatusEnum.SkiingAlps
							});

            //Status = user.IsOnline
            //                                ? DetailsViewModel.StatusEnum.Online
            //                                : !user.IsApproved
            //                                    ? DetailsViewModel.StatusEnum.Unapproved
            //                                    : user.IsLockedOut
            //                                        ? DetailsViewModel.StatusEnum.LockedOut
            //                                        : DetailsViewModel.StatusEnum.Offline

        }

		public ViewResult Password(Guid id)
		{
			var user = _userService.Get(id);
			var userRoles = _rolesService.Enabled
				? _rolesService.FindByUser(user)
				: Enumerable.Empty<string>();
			return View(new DetailsViewModel
			{
				CanResetPassword = _membershipSettings.Password.ResetOrRetrieval.CanReset,
				RequirePasswordQuestionAnswerToResetPassword = _membershipSettings.Password.ResetOrRetrieval.RequiresQuestionAndAnswer,
				DisplayName = user.UserName,
				//User = user,
				//Roles = _rolesService.Enabled
				//	? _rolesService.FindAll().ToDictionary(role => role, role => userRoles.Contains(role))
				//	: new Dictionary<string, bool>(0),
				//IsRolesEnabled = _rolesService.Enabled,
				//Status = user.IsOnline
				//			? DetailsViewModel.StatusEnum.Online
				//			: !user.IsApproved
				//				? DetailsViewModel.StatusEnum.Unapproved
				//				: user.IsLockedOut
				//					? DetailsViewModel.StatusEnum.LockedOut
				//					: DetailsViewModel.StatusEnum.Offline
			});
		}

		public ViewResult UsersRoles(Guid id)
		{
            var userService = new AspNetMembershipProviderWrapper();
            var user = userService.SignInManager.UserManager.Users.FirstOrDefault(w => w.Id == id.ToString());
            Dictionary<string, string> rolls = user.Roles.ToDictionary(role => role.RoleId, role => userService.RoleManager.FindByIdAsync(role.RoleId).Result.Name);

            return View(new DetailsViewModel
			{
				//CanResetPassword = _membershipSettings.Password.ResetOrRetrieval.CanReset,
				//RequirePasswordQuestionAnswerToResetPassword = _membershipSettings.Password.ResetOrRetrieval.RequiresQuestionAndAnswer,
				DisplayName = user.UserName,
				User = user,
				Roles = user.Roles.ToList(),
                Rolls = rolls,
				IsRolesEnabled = true,
				Status = DetailsViewModel.StatusEnum.FlyingAlaska
			});
		}

		public ViewResult CreateUser()
		{
			var model = new CreateUserViewModel
			            	{
			            		InitialRoles = _rolesService.FindAll().ToDictionary(k => k, v => false)
			            	};
			return View(model);
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public ActionResult CreateUser(CreateUserViewModel createUserViewModel)
		{
			if (!ModelState.IsValid)
				return View(createUserViewModel);

			try
			{
				if(createUserViewModel.Password != createUserViewModel.ConfirmPassword)
					throw new MembershipCreateUserException("Passwords do not match.");

				var user = _userService.Create(
					createUserViewModel.Username,
					createUserViewModel.Password,
					createUserViewModel.Email,
					createUserViewModel.PasswordQuestion,
					createUserViewModel.PasswordAnswer,
					true);

				if (createUserViewModel.InitialRoles != null)
				{
					var rolesToAddUserTo = createUserViewModel.InitialRoles.Where(x => x.Value).Select(x => x.Key);
					foreach (var role in rolesToAddUserTo)
						_rolesService.AddToRole(user, role);					
				}

				return RedirectToAction("Details", new { id = user.ProviderUserKey });
			}
			catch (MembershipCreateUserException e)
			{
				ModelState.AddModelError(string.Empty, e.Message);
				return View(createUserViewModel);
			}
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult Details(Guid id, string email, string comments)
		{
			var user = _userService.Get(id);
			user.Email = email;
			user.Comment = comments;
			_userService.Update(user);
			return RedirectToAction("Details", new { id });
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult DeleteUser(Guid id)
		{
			var user = _userService.Get(id);

			if (_rolesService.Enabled)
				_rolesService.RemoveFromAllRoles(user);
			_userService.Delete(user);
			return RedirectToAction("Index");
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult ChangeApproval(Guid id, bool isApproved)
		{
			var user = _userService.Get(id);

AliceApi/Areas/MvcMembership/Views/UserAdministration/CreateUser.cshtml
@model AliceApi.Areas.MvcMembership.Models.UserAdministration.CreateUserViewModel
@{
	ViewBag.Title = "Create New User";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href='@Url.Content("~/Content/MvcMembership.css")' rel="stylesheet" type="text/css" />

<h2 class="mvcMembership">Create New User</h2>

<div class="mvcMembership-account">
	@using(Html.BeginForm("CreateUser", "UserAdministration")){ 
		@Html.ValidationSummary(true)

	 	<fieldset>
			@Html.EditorForModel()
		</fieldset>

		if (Model.InitialRoles.Count > 0) {
			<fieldset>
				<h3 class="mvcMembership">Initial Roles</h3>
				@for(var i = 0; i < Model.InitialRoles.Count; i++){ 
					var role = Model.InitialRoles.ElementAt(i);
					<div>
						<input name="InitialRoles[@i].Key" type="hidden" value="@role.Key" />
						<label>@Html.CheckBox("InitialRoles[" + i + "].Value", role.Value) @role.Key</label>
					</div>
				}
			</fieldset>
		}
	 
		<input type="submit" value="Create" />
	} 
</div>

AliceApi/Areas/MvcMembership/Views/UserAdministration/Details.cshtml
@using System.Globalization
@model AliceApi.Areas.MvcMembership.Models.UserAdministration.DetailsViewModel
@{
	ViewBag.Title = "User Details: " + Model.DisplayName;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<link href='@Url.Content("~/Areas/MvcMembership/Content/MvcMembership.css")' rel="stylesheet" type="text/css" />
<div class="title">
    <h1>Membership</h1>
    <h2>User Details</h2>
</div>*@

<h2>User Administration<br/>
<small>User Details: @Model.DisplayName [@Model.Status]</small></h2>

<ul class="list-inline">
	<li>Details</li>
	<li>@Html.ActionLink("Password", "Password", "UserAdministration", new { id = Model.User.Id }, null)</li>
	@if(Model.IsRolesEnabled){
	<li>@Html.ActionLink("Roles", "UsersRoles", "UserAdministration", new { id = Model.User.Id }, null)</li>
	}
</ul>

<h3>Account</h3>
<div>
	<dl>
		<dt>User Name:</dt>
			<dd>@Model.User.UserName</dd>
		<dt>Email Address:</dt>
			<dd><a href="mailto:@Model.User.Email">@Model.User.Email</a></dd>
		@*@if(Model.User.LastActivityDate == Model.User.CreationDate){
		<dt>Last Active:</dt>
			<dd><em>Never</em></dd>
		<dt>Last Login:</dt>
			<dd><em>Never</em></dd>
		}else{
		<dt>Last Active:</dt>
			<dd>@Model.User.LastActivityDate.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</dd>
		<dt>Last Login:</dt>
			<dd>@Model.User.LastLoginDate.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</dd>
		}
		<dt>Created:</dt>
			<dd>@Model.User.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</dd>*@
	</dl>

	@using(Html.BeginForm("ChangeApproval", "UserAdministration", new{ id = Model.User.Id })){
		@Html.Hidden("isApproved", !Model.User.LockoutEnabled)
		<input type="submit" value='@(Model.User.LockoutEnabled ? "Unapprove" : "Approve") Account' />
	}
	@using(Html.BeginForm("DeleteUser", "UserAdministration", new{ id = Model.User.Id })){
		<input type="submit" value="Delete Account" />
	}
</div>

<h3>Email Address & Comments</h3>
<div>
	@using(Html.BeginForm("Details", "UserAdministration", new{ id = Model.User.Id })){
	<fieldset>
		<p>
			<label for="email">Email Address:</label>
			@Html.TextBox("email", Model.User.Email)
		</p>
		@*<p>
			<label for="comments">Comments:</label>
			@Html.TextArea("comments", Model.User.Comment)
		</p>*@
		<input type="submit" value="Save Email Address and Comments" />
	</fieldset>
	}
</div>

AliceApi/Areas/MvcMembership/Views/UserAdministration/Index.cshtml
@using PagedList.Mvc
@model AliceApi.Areas.MvcMembership.Models.UserAdministration.IndexViewModel
@{
	ViewBag.Title = "User Administration";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@if(!Model.IsRolesEnabled){
	<p>WARNING: Your Role Provider is currently disabled - any user may currently visit this page.<br />Change &lt;roleManager enabled="false"&gt; to &lt;roleManager enabled="true"&gt; in your web.config file.</p>
}

<h2>User Administration</h2>

<h3>Find a User
	@if (!string.IsNullOrWhiteSpace(Model.Search)) { 
		<span>(@Html.ActionLink("Clear Search", "Index"))</span>
	}
</h3>
<form method="get">
	<fieldset><legend></legend>
		<label>
			User Name or Email Address:
			<input type="text" name="search" value="@Model.Search" />
			<input type="submit" value="Search" />
		</label>
	</fieldset>
</form>
	
<h3>Users (@Html.ActionLink("New User", "CreateUser", "UserAdministration"))</h3>
<div>
@if(Model.Users.Count > 0){
	<ul>
		@foreach(var user in Model.Users){
		<li>
			<span class="mvcMembership-username">@Html.ActionLink(user.UserName, "Details", new{ id = user.Id})</span>
			<span class="mvcMembership-email"><a href="mailto:@user.Email">@user.Email</a></span>
			@*@if(user.IsOnline){
				<span class="mvcMembership-isOnline">Online</span>
			}else{
				<span class="mvcMembership-isOffline">Offline for
					@{
						var offlineSince = (DateTime.Now - user.LastActivityDate);
						if (offlineSince.TotalSeconds <= 60){
							<text>1 minute.</text>
						}else if(offlineSince.TotalMinutes < 60){
							<text>@Math.Floor(offlineSince.TotalMinutes) minutes.</text>
						}else if (offlineSince.TotalMinutes < 120){
							<text>1 hour</text>
						}else if (offlineSince.TotalHours < 24){
							<text>@Math.Floor(offlineSince.TotalHours) hours.</text>
						}else if (offlineSince.TotalHours < 48){
							<text>1 day.</text>
						}else{
							<text>@Math.Floor(offlineSince.TotalDays) days.</text>
						}
					}
				</span>
			}*@
			@*@if(!string.IsNullOrEmpty(user.Comment)){
				<span class="mvcMembership-comment">@user.Comment</span>
			}*@
		</li>
		}
	</ul>
	@Html.PagedListPager(Model.Users, page => Url.Action("Index", new { page, search = Model.Search }))
}else{
	<p>No users have registered.</p>
}
</div>

@if(Model.IsRolesEnabled){
    <h3>Roles</h3>
    <hr />
	<div>
	@if(Model.Roles.Any() ){
		<ul>
			@foreach(var role in Model.Roles){
			<li>
				@Html.ActionLink(role.Name, "Role", new{id = role.Id})
				@using(Html.BeginForm("DeleteRole", "UserAdministration", new{id=role.Id})){
				<input type="submit" value="Delete" />
				}
			</li>
			}
		</ul>
	}else{
		<p>No roles have been created.</p>
	}

	@using(Html.BeginForm("CreateRole", "UserAdministration")){
		<fieldset>
			<label>Role:</label>
			@Html.TextBox("name")
			<input type="submit" value="Create Role" />
		</fieldset>
	}
	</div>
}

AliceApi/Areas/MvcMembership/Views/UserAdministration/Password.cshtml
@using System.Globalization
@model AliceApi.Areas.MvcMembership.Models.UserAdministration.DetailsViewModel
@{
	ViewBag.Title = "User Details: " + Model.DisplayName;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href='@Url.Content("~/Content/MvcMembership.css")' rel="stylesheet" type="text/css" />

<h2 class="mvcMembership">User Details: @Model.DisplayName [@Model.Status]</h2>

<ul class="mvcMembership-tabs">
	<li>@Html.ActionLink("Details", "Details", "UserAdministration", new {id = Model.User.ProviderUserKey }, null)</li>
	<li>Password</li>
	@if(Model.IsRolesEnabled){
	<li>@Html.ActionLink("Roles", "UsersRoles", "UserAdministration", new{id = Model.User.ProviderUserKey}, null)</li>
	}
</ul>

<h3 class="mvcMembership">Password</h3>
<div class="mvcMembership-password">
	@if(Model.User.IsLockedOut){
		<p>Locked out since @Model.User.LastLockoutDate.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</p>
		using(Html.BeginForm("Unlock", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
		<input type="submit" value="Unlock Account" />
		}
	}else{

		if(Model.User.LastPasswordChangedDate == Model.User.CreationDate){
		<dl class="mvcMembership">
			<dt>Last Changed:</dt>
			<dd><em>Never</em></dd>
		</dl>
		}else{
		<dl class="mvcMembership">
			<dt>Last Changed:</dt>
			<dd>@Model.User.LastPasswordChangedDate.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</dd>
		</dl>
		}

		if(Model.CanResetPassword && Model.RequirePasswordQuestionAnswerToResetPassword){
			using(Html.BeginForm("ResetPasswordWithAnswer", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
			<fieldset>
				<p>
					<dl class="mvcMembership">
						<dt>Password Question:</dt>
						if(string.IsNullOrEmpty(Model.User.PasswordQuestion) || string.IsNullOrEmpty(Model.User.PasswordQuestion.Trim())){
						<dd><em>No password question defined.</em></dd>
						}else{
						<dd>@Model.User.PasswordQuestion</dd>
						}
					</dl>
				</p>
				<p>
					<label for="answer">Password Answer:</label>
					@Html.TextBox("answer")
				</p>
				<input type="submit" value="Reset to Random Password and Email User" />
			</fieldset>
			}
		}else if(Model.CanResetPassword){
			using(Html.BeginForm("SetPassword", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
			<fieldset>
				<p>
					<label for="password">New Password:</label>
					@Html.TextBox("password")
				</p>
				<input type="submit" value="Change Password" />
			</fieldset>
			}
			using(Html.BeginForm("ResetPassword", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
			<fieldset>
				<input type="submit" value="Reset to Random Password and Email User" />
			</fieldset>
			}
		}

	}
</div>

AliceApi/Areas/MvcMembership/Views/UserAdministration/Role.cshtml
@model AliceApi.Areas.MvcMembership.Models.UserAdministration.RoleViewModel
@{
	ViewBag.Title = "Role: " + Model.Role;
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Role Manager</h3>
<h4>Selected Role: @Model.Role</h4>

	@if(Model.Users.Any()){
		<ul>
			@foreach(var user in Model.Users){ //var user = Model.Users[key];
			<li>
				@if(user == null){
					<span>@user.UserName <em>(Deleted)</em></span>
				}else{
					@Html.ActionLink(user.UserName, "Details", new{id=user.Id})
					using(Html.BeginForm("RemoveFromRole", "UserAdministration", new{id = user.Id, role = Model.Role})){
						<input type="submit" value="Remove From" />
					}
				}
			</li>
			}
		</ul>
	}else{
	<p>No users are in this role.</p>
	}

AliceApi/Areas/MvcMembership/Views/UserAdministration/UsersRoles.cshtml
@using System.Globalization
@model AliceApi.Areas.MvcMembership.Models.UserAdministration.DetailsViewModel
@{
	ViewBag.Title = "User Details: " + Model.DisplayName;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Administration<br/>
    <small>User Details: @Model.DisplayName [@Model.Status]</small></h2>

<ul class="list-inline">
	<li>@Html.ActionLink("Details", "Details", "UserAdministration", new { id = Model.User.Id }, null)</li>
	<li>@Html.ActionLink("Password", "Password", "UserAdministration", new { id = Model.User.Id }, null)</li>
	<li>Roles</li>
</ul>

<h3>Roles</h3>
<div>
    <ul>
        @foreach (var role in Model.Rolls)
        {
            <li>
                @Html.ActionLink(role.Value, "Role", new {id = role.Key})
                @if (role.Key.Length > 0)
                {
                    using (Html.BeginForm("RemoveFromRole", "UserAdministration", new {id = Model.User.Id, role = role.Key}))
                    {
                        <input type="submit" value="Remove From"/>
                    }
                }
                else
                {
                    using (Html.BeginForm("AddToRole", "UserAdministration", new {id = Model.User.Id, role = role.Key}))
                    {
                        <input type="submit" value="Add To"/>
                    }
                }
            </li>
        }
    </ul>


    <div class="row">
        <div class="col-md-3">
            <label>Available Roles</label>
            <textarea rows="10" cols="20"></textarea>
        </div>
        <div class="col-md-2">
            <br/><br/>
            <input type="button" value="< remove" style="width: 100px;"/><br/>
            <input type="button" value="add >" style="width: 100px;"/>
        </div>
        <div class="col-md-3">
            <label>Roles Assigned</label>
            <textarea rows="10" cols="20"></textarea>
        </div>



    </div>


</div>